---
title: "Exploring NOAA databases: the health and economic effects of severe weather in the United States"
author: "Glenn Kerbein"
date: "March 14, 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Synopsis

Storms and other severe weather events can cause both public health and economic problems for communities and municipalities.

This report centers around the U.S. National Oceanic and Atmospheric Administration's (NOAA) storm database. This database tracks characteristics of major storms and weather events in the United States, including when and where they occur, as well as estimates of any fatalities, injuries, and property damage.

### The data analysis must address the following:

1. Across the United States, which types of events (as indicated in the ```EVTYPE``` variable) are most harmful with respect to population health?
2. Across the United States, which types of events have the greatest economic consequences?

### By aggregating the data by storm event type, this analysis shows:

* Tornados are the most harmfull events on population health (including injury and fatalities).
* Floods are responsible for the most economic damage.

## Data Processing

### 1. Session reproducability

```
sessionInfo()
```

```
rm(list=ls(all=TRUE))
```

### 2. Required packages

```
library(dplyr, quietly = T, warn.conflicts = F)
library(ggplot2, quietly = T, warn.conflicts = F)
```

#### Download
The NOAA database file is made available in a compressed bzip2 file, containing a master CSV file. The CSV contains all relevant data.

```
# Get required files
datafile <- "storm.csv.bz2"
if(!file.exists(datafile)){
  url <- "https://d396qusza40orc.cloudfront.net/repdata%2Fdata%2FStormData.csv.bz2"
  download.file(
    url,
    destfile = datafile,
    method = "curl",
    quiet = TRUE
  )
}
```
#### Reading the data
```
stormdata <- read.csv(datafile, header = TRUE)
```

#### Clean the data

Subset the data to calculate given relevant column information.

```
stormdata.clean <- stormdata[,c('EVTYPE','FATALITIES','INJURIES', 'PROPDMG', 'PROPDMGEXP', 'CROPDMG', 'CROPDMGEXP', 'STATE')]
```

#### Upstream Documentation
Some database documentation has been made available:

* [National Weather Service Storm Data Documentation](https://d396qusza40orc.cloudfront.net/repdata%2Fpeer2_doc%2Fpd01016005curr.pdf)
* [National Climatic Data Center Storm Events FAQ](https://d396qusza40orc.cloudfront.net/repdata%2Fpeer2_doc%2FNCDC%20Storm%20Events-FAQ%20Page.pdf])

The events in the database start in the year 1950 and end in November 2011. In the earlier years of the database there are generally fewer events recorded, most likely due to a lack of good records. More recent years should be considered more complete.


#### Scale Cleaned Data

```
#scale data appropriately
# Convert H, K, M, B units to calculate Property Damage
stormdata.clean$PROPDMGNUM = 0
stormdata.clean[stormdata.clean$PROPDMGEXP == "H", ]$PROPDMGNUM = stormdata.clean[stormdata.clean$PROPDMGEXP == "H", ]$PROPDMG * 10^2
stormdata.clean[stormdata.clean$PROPDMGEXP == "K", ]$PROPDMGNUM = stormdata.clean[stormdata.clean$PROPDMGEXP == "K", ]$PROPDMG * 10^3
stormdata.clean[stormdata.clean$PROPDMGEXP == "M", ]$PROPDMGNUM = stormdata.clean[stormdata.clean$PROPDMGEXP == "M", ]$PROPDMG * 10^6
stormdata.clean[stormdata.clean$PROPDMGEXP == "B", ]$PROPDMGNUM = stormdata.clean[stormdata.clean$PROPDMGEXP == "B", ]$PROPDMG * 10^9
# Convert H, K, M, B units to calculate Crop Damage
stormdata.clean$CROPDMGNUM = 0
stormdata.clean[stormdata.clean$CROPDMGEXP == "H", ]$CROPDMGNUM = stormdata.clean[stormdata.clean$CROPDMGEXP == "H", ]$CROPDMG * 10^2
stormdata.clean[stormdata.clean$CROPDMGEXP == "K", ]$CROPDMGNUM = stormdata.clean[stormdata.clean$CROPDMGEXP == "K", ]$CROPDMG * 10^3
stormdata.clean[stormdata.clean$CROPDMGEXP == "M", ]$CROPDMGNUM = stormdata.clean[stormdata.clean$CROPDMGEXP == "M", ]$CROPDMG * 10^6
stormdata.clean[stormdata.clean$CROPDMGEXP == "B", ]$CROPDMGNUM = stormdata.clean[stormdata.clean$CROPDMGEXP == "B", ]$CROPDMG * 10^9
```

#### Exploring event types

Double-check our work, making sure to capture relevant events.

```
event.type<-stormdata.clean %>% 
	group_by(EVTYPE) %>%
	summarize(n=n()) %>% 
	arrange(desc(n))
event.type
```

As we can see, there are multiple events that have ambiguous names but could easily be included in our dataset. To rectify, conglomerate into intuitive names.

```
stormdata.clean$EVTYPE <- gsub("^(HEAT).*", "HEAT", stormdata.clean$EVTYPE)
stormdata.clean$EVTYPE <- gsub("^(RECORD HEAT).*", "HEAT", stormdata.clean$EVTYPE)
stormdata.clean$EVTYPE <- gsub("^(EXTREME HEAT).*", "HEAT", stormdata.clean$EVTYPE)
stormdata.clean$EVTYPE <- gsub("^(Heat).*", "HEAT", stormdata.clean$EVTYPE)
stormdata.clean$EVTYPE <- gsub("^(EXCESSIVE HEAT).*", "HEAT", stormdata.clean$EVTYPE)
stormdata.clean$EVTYPE <- gsub("^(TSTM).*", "THUNDER STORM", stormdata.clean$EVTYPE)
stormdata.clean$EVTYPE <- gsub("^(THUNDERSTORM).*", "THUNDER STORM", stormdata.clean$EVTYPE)
stormdata.clean$EVTYPE <- gsub("^(TROPICAL STORM).*", "TROPICAL STORM", stormdata.clean$EVTYPE)
stormdata.clean$EVTYPE <- gsub("^(FLASH FLOOD).*", "FLOOD", stormdata.clean$EVTYPE)
stormdata.clean$EVTYPE <- gsub("^(WIND).*", "WIND", stormdata.clean$EVTYPE)
stormdata.clean$EVTYPE <- gsub("^(STRONG WIND).*", "WIND", stormdata.clean$EVTYPE)
stormdata.clean$EVTYPE <- gsub("^(HIGH WIND).*", "WIND", stormdata.clean$EVTYPE)
stormdata.clean$EVTYPE <- gsub("^(HURRICANE).*", "HURICCANE", stormdata.clean$EVTYPE)
stormdata.clean$EVTYPE <- gsub("^(SNOW).*", "SNOW", stormdata.clean$EVTYPE)
stormdata.clean$EVTYPE <- gsub("^(HEAVY SNOW).*", "SNOW", stormdata.clean$EVTYPE)
stormdata.clean$EVTYPE <- gsub("^(FIRE).*", "FIRE", stormdata.clean$EVTYPE)
stormdata.clean$EVTYPE <- gsub("^(WILD/FOREST FIRE).*", "FIRE", stormdata.clean$EVTYPE)
stormdata.clean$EVTYPE <- gsub("^(WILDFIRE).*", "FIRE", stormdata.clean$EVTYPE)
stormdata.clean$EVTYPE <- gsub("^(WILD FIRES).*", "FIRE", stormdata.clean$EVTYPE)
stormdata.clean$EVTYPE <- gsub("^(HAIL).*", "HAIL", stormdata.clean$EVTYPE)
stormdata.clean$EVTYPE <- gsub("^(BLIZZARD).*", "BLIZZARD", stormdata.clean$EVTYPE)
stormdata.clean$EVTYPE <- gsub("^(COLD).*", "COLD", stormdata.clean$EVTYPE)
stormdata.clean$EVTYPE <- gsub("^(WINTER WEATHER).*", "COLD", stormdata.clean$EVTYPE)
stormdata.clean$EVTYPE <- gsub("^(EXTREME COLD).*", "COLD", stormdata.clean$EVTYPE)
stormdata.clean$EVTYPE <- gsub("^(RIP).*", "RIP", stormdata.clean$EVTYPE)
stormdata.clean$EVTYPE <- gsub("^(FOG).*", "FOG", stormdata.clean$EVTYPE)
stormdata.clean$EVTYPE <- gsub("^(DENSE FOG).*", "FOG", stormdata.clean$EVTYPE)
stormdata.clean$EVTYPE <- gsub("^(AVALANCHE).*", "AVALANCHE", stormdata.clean$EVTYPE)
stormdata.clean$EVTYPE <- gsub("^(AVALANCE).*", "AVALANCHE", stormdata.clean$EVTYPE)
stormdata.clean$EVTYPE <- gsub("^(RAIN).*", "RAIN", stormdata.clean$EVTYPE)
stormdata.clean$EVTYPE <- gsub("^(HEAVY RAIN).*", "RAIN", stormdata.clean$EVTYPE)
stormdata.clean$EVTYPE <- gsub("^(HIGH SURF).*", "SURF", stormdata.clean$EVTYPE)
stormdata.clean$EVTYPE <- gsub("^(HEAVY SURF).*", "SURF", stormdata.clean$EVTYPE)
stormdata.clean$EVTYPE <- gsub("^(SURF).*", "SURF", stormdata.clean$EVTYPE)
```

## Results

### Across the United States, which types of events (as indicated in the ```EVTYPE``` variable) are most harmful with respect to population health?


```
fatalities <- aggregate(FATALITIES ~ EVTYPE, data=tidyNOAA, sum)
fatalities <- fatalities[order(-fatalities$FATALITIES), ][1:10, ]
fatalities$EVTYPE <- factor(fatalities$EVTYPE, levels = fatalities$EVTYPE)

ggplot(fatalities, aes(x = EVTYPE, y = FATALITIES)) + 
    geom_bar(stat = "identity", fill = "blue") + 
    theme(axis.text.x = element_text(angle = 90, hjust = 1)) + 
    xlab("Event Type") + ylab("Fatalities") + ggtitle("Number of fatalities by top 10 Weather Events")
```

```
injuries <- aggregate(INJURIES ~ EVTYPE, data=tidyNOAA, sum)
injuries <- injuries[order(-injuries$INJURIES), ][1:10, ]
injuries$EVTYPE <- factor(injuries$EVTYPE, levels = injuries$EVTYPE)

ggplot(injuries, aes(x = EVTYPE, y = INJURIES)) + 
    geom_bar(stat = "identity", fill = "blue") + 
    theme(axis.text.x = element_text(angle = 90, hjust = 1)) + 
    xlab("Event Type") + ylab("Injuries") + ggtitle("Number of injuries by top 10 Weather Events")
```

### Across the United States, which types of events have the greatest economic consequences?

